

# 时间线

## xg-risk-rmq-1

- 12:03:15 开始，连接建立速率开始增加，初始为 10+ 连接/秒
- 12:04:00 左右，连接建立速率达到最高峰 100+ 连接/秒
- 12:04:20 左右，连接建立速率降回 10+ 连接/秒
- 12:05:22 出现 1 次 {badmatch,{error,{channel_operation_timeout,5000}}}
- 12:05:41 出现 2 次 {badmatch,{error,{channel_operation_timeout,5000}}}
- 12:05:43 出现 1 次 {badmatch,{error,{channel_operation_timeout,5000}}}
- 12:14:42 出现 4 次 killed
- 12:19:05 出现 1 次 killed
- 12:19:06 出现 7 次 killed
- 12:20:20 出现 8 次 channel_termination_timeout


### 连接创建和分布情况

在 12:05:22 时间点之前，能够看到的只有向 xg-risk-rmq-1 建立大量连接的情况；
此时日志中没有特别的异常；

大致连接波动情况如下：

（略）

### 错误日志解析

在 sasl 日志中看到，从 12:05:22  开始出现 `CRASH REPORT` ；

其中
- 12:05:22 出现 1 次；
- 12:05:41 出现 2 次；
- 12:05:43 出现 1 次；

#### 错误日志

在 sasl 日志中有

```shell
=CRASH REPORT==== 3-Sep-2016::12:05:22 ===
  crasher:
    initial call: gen:init_it/6
    pid: <0.18881.6190>            %% 发生 crash 进程的 pid
    registered_name: []
    exception exit: {{badmatch,{error,{channel_operation_timeout,5000}}},
                     [{rabbit_channel,terminate,2,
                                      [{file,"src/rabbit_channel.erl"},
                                       {line,614}]},
                      {gen_server2,terminate,3,
                                   [{file,"src/gen_server2.erl"},{line,1146}]},
                      {proc_lib,wake_up,3,
                                [{file,"proc_lib.erl"},{line,249}]}]}
      in function  gen_server2:terminate/3 (src/gen_server2.erl, line 1149)
    ancestors: [<0.3384.6141>,<0.6490.6193>,<0.8898.6179>,<0.12511.7656>,
                  <0.25522.2>,<0.25521.2>,<0.25520.2>,rabbit_sup,<0.25348.2>]
    messages: []
    links: []
    dictionary: [{{queue_stats,
                       {resource,<<"risk">>,queue,<<"asynctomongo">>}},
                   [{ack,1912117},{deliver,1912117},{redeliver,28}]},
                  {guid_secure,
                      {{2,'rabbit@xg-risk-rmq-1',#Ref<0.0.297033.218495>},0}},
                  {channel_operation_timeout,5000},
                  {msg_size_for_gc,257154},
                  {process_name,
                      {rabbit_channel,
                          {<<"10.0.29.66:20231 -> 10.0.22.20:5672">>,1}}}]
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 235923352
  neighbours:

=SUPERVISOR REPORT==== 3-Sep-2016::12:05:22 ===
     Supervisor: {<0.3384.6141>,rabbit_channel_sup}
     Context:    shutdown_error
     Reason:     {{badmatch,{error,{channel_operation_timeout,5000}}},
                  [{rabbit_channel,terminate,2,
                                   [{file,"src/rabbit_channel.erl"},
                                    {line,614}]},
                   {gen_server2,terminate,3,
                                [{file,"src/gen_server2.erl"},{line,1146}]},
                   {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,249}]}]}
     Offender:   [{pid,<0.18881.6190>},      %% 发生 crash 进程的 pid
                  {name,channel},
                  {mfargs,
                      {rabbit_channel,start_link,
                          [1,<0.8093.6184>,<0.19131.6174>,<0.8093.6184>,
                           <<"10.0.29.66:20231 -> 10.0.22.20:5672">>,
                           rabbit_framing_amqp_0_9_1,
                           {user,<<"risk">>,
                               [monitoring],
                               [{rabbit_auth_backend_internal,none}]},
                           <<"risk">>,
                           [{<<"exchange_exchange_bindings">>,bool,true},
                            {<<"connection.blocked">>,bool,true},
                            {<<"authentication_failure_close">>,bool,true},
                            {<<"basic.nack">>,bool,true},
                            {<<"publisher_confirms">>,bool,true},
                            {<<"consumer_cancel_notify">>,bool,true}],
                           <0.2544.148>,<0.24394.5787>]}},
                  {restart_type,intrinsic},
                  {shutdown,70000},
                  {child_type,worker}]
```

对应 log 日志中的内容如下

```shell
=ERROR REPORT==== 3-Sep-2016::12:05:22 ===
** Generic server <0.18881.6190> terminating

%% 因为 <0.3384.6141> 对应 rabbit_channel_sup 进程
%% 因此下面信息表明了：当前 channel 进程终止的原因是由于 rabbit_channel_sup 发送了 {'EXIT',<0.3384.6141>,shutdown} 消息；

** Last message in was {'EXIT',<0.3384.6141>,shutdown}
** When Server state == {ch,running,rabbit_framing_amqp_0_9_1,1,
                         <0.8093.6184>,<0.19131.6174>,<0.8093.6184>,
                         <<"10.0.29.66:20231 -> 10.0.22.20:5672">>,
                         {lstate,<0.24394.5787>,false},
                         none,1912118,
                         {[],[]},
                         {user,<<"risk">>,
                          [monitoring],
                          [{rabbit_auth_backend_internal,none}]},
                         <<"risk">>,<<"asynctomongo">>,
                         {dict,1,16,16,8,80,48,
                          {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                          {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                            [[<0.19961.156>|
                              {resource,<<"risk">>,queue,<<"asynctomongo">>}]],
                            []}}},
                         {state,
                          {dict,1,16,16,8,80,48,
                           {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                           {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                             [[<0.19961.156>|#Ref<0.0.297033.218499>]],
                             []}}},
                          erlang},
                         {dict,1,16,16,8,80,48,
                          {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                          {{[],[],[],[],[],[],[],[],[],[],[],
                            [[<<"amq.ctag-yVL9PsI6oqYtBhih3p2LiQ">>|
                              {{amqqueue,
                                {resource,<<"risk">>,queue,<<"asynctomongo">>},
                                false,false,none,[],<0.19961.156>,[],[],[],
                                undefined,[],[],live},
                               {false,16,false,[]}}]],
                            [],[],[],[]}}},
                         {dict,1,16,16,8,80,48,
                          {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                          {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                            [[<0.19961.156>|
                              {1,
                               {<<"amq.ctag-yVL9PsI6oqYtBhih3p2LiQ">>,nil,
                                nil}}]],
                            []}}},
                         {set,1,16,16,8,80,48,
                          {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                          {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                            [<0.19961.156>],
                            []}}},
                         <0.2544.148>,
                         {state,fine,5000,undefined},
                         false,1,
                         {{0,nil},{0,nil}},
                         [],
                         {{0,nil},{0,nil}},
                         [{<<"exchange_exchange_bindings">>,bool,true},
                          {<<"connection.blocked">>,bool,true},
                          {<<"authentication_failure_close">>,bool,true},
                          {<<"basic.nack">>,bool,true},
                          {<<"publisher_confirms">>,bool,true},
                          {<<"consumer_cancel_notify">>,bool,true}],
                         none,16,none,flow,[]}
** Reason for termination == 
** {{badmatch,{error,{channel_operation_timeout,5000}}},
    [{rabbit_channel,terminate,2,[{file,"src/rabbit_channel.erl"},{line,614}]},
     {gen_server2,terminate,3,[{file,"src/gen_server2.erl"},{line,1146}]},
     {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,249}]}]}
** In 'terminate' callback with reason ==
** shutdown
```

#### 源码分析

在 `proc_lib.erl` 中

```erlang
wake_up(M, F, A) when is_atom(M), is_atom(F), is_list(A) ->
    try
	    %% 调用 gen_server2:terminate/3 的地方
        apply(M, F, A) 
    catch
        Class:Reason ->
            exit_p(Class, Reason)
    end.

%% 在以 Reason 原因退出前，先发出 crash 报告
exit_p(Class, Reason) ->
    case get('$initial_call') of
        {M,F,A} when is_atom(M), is_atom(F), is_integer(A) ->
            MFA = {M,F,make_dummy_args(A, [])},
            crash_report(Class, Reason, MFA),
            exit(Reason);
        _ ->
            %% The process dictionary has been cleared or
            %% possibly modified.
            crash_report(Class, Reason, []),
            exit(Reason)
    end.
...

%% -----------------------------------------------------
%% Generate a crash report.
%% -----------------------------------------------------

crash_report(exit, normal, _)       -> ok;
crash_report(exit, shutdown, _)     -> ok;
crash_report(exit, {shutdown,_}, _) -> ok;
%% 处理异常退出情况
crash_report(Class, Reason, StartF) ->
    OwnReport = my_info(Class, Reason, StartF),
    LinkReport = linked_info(self()),
    Rep = [OwnReport,LinkReport],
    %% 输出 crash report 的地方
    error_logger:error_report(crash_report, Rep).

```

在 `gen_server2.erl` 中

```erlang
%%% ---------------------------------------------------
%%% Terminate the server.
%%% ---------------------------------------------------

%% 对应上面调用 apply(M, F, A) 的地方
terminate(Reason, Msg, #gs2_state { name  = Name,
                                    mod   = Mod,
                                    state = State,
                                    debug = Debug }) ->
    %% 根据上下文，这里有
    %% Mod => rabbit_channel
    %% Reason => shutdown
    case catch Mod:terminate(Reason, State) of
        {'EXIT', R} ->  %% 在终止的过程中抛出异常
	        %% 输出 =ERROR REPORT==== 信息
            error_info(R, Reason, Name, Msg, State, Debug),
            exit(R);
        _ ->
            case Reason of
                normal ->
                    exit(normal);
                shutdown ->
                    exit(shutdown);
                {shutdown,_}=Shutdown ->
                    exit(Shutdown);
                _ ->
                    error_info(Reason, undefined, Name, Msg, State, Debug),
                    exit(Reason)
            end
    end.
```

在 `rabbit_channel.erl` 中

```erlang
terminate(Reason, State) ->
    %% 当前 channel 在终止时，需要通知与自身相关的所有 queue
    %% 对应的 queue 可能存在于 本地 和 远端 节点 

	%% 在当前上下文中，这里会的到
    %% Res => {error, {channel_operation_timeout, Timeout}}
    {Res, _State1} = notify_queues(State),
    %% 若 Reason 为 normal|shutdown|{shutdown,_Term} 中的一种，则 Res 必须为 ok ，否则触发 badmatch 异常
    case Reason of
        normal            -> ok = Res;
        shutdown          -> ok = Res;
        {shutdown, _Term} -> ok = Res;
        _                 -> ok
    end,
    pg_local:leave(rabbit_channels, self()),
    rabbit_event:if_enabled(State, #ch.stats_timer,
                            fun() -> emit_stats(State) end),
    rabbit_event:notify(channel_closed, [{pid, self()}]).

...

%% 向所有与当前 channel 有关的 queue 通知自己要挂了
notify_queues(State = #ch{state = closing}) ->
    {ok, State};
notify_queues(State = #ch{consumer_mapping  = Consumers,
                          delivering_queues = DQ }) ->
    %% 获取与当前 channel 相关的 queue 的 pid
    QPids = sets:to_list(
              sets:union(sets:from_list(consumer_queues(Consumers)), DQ)),
    %% 向所有与自己（当前 channel）有关的 queue 通知自己已经要挂了（closing）
    %% 根据上下文，这里得到了 {{error, {channel_operation_timeout, Timeout}}, State#ch{state = closing}} 这个结果
    {rabbit_amqqueue:notify_down_all(QPids, self(),
                                     get(channel_operation_timeout)),
     State#ch{state = closing}}.
```

在 `rabbit_amqqueue.erl` 中

```erlang
%% Timeout => 默认为 ?CHANNEL_OPERATION_TIMEOUT 即 5 秒超时；
notify_down_all(QPids, ChPid, Timeout) ->
	%% 基于 rpc 调用本地节点上的 delegate:call/2 再由 delegate 进程负责
	%% 将 channel 的 down 消息通知给所有相关的 queue 进程（本地节点＋远端节点）
    case rpc:call(node(), delegate, call,
                  [QPids, {notify_down, ChPid}], Timeout) of
        %% 在这里触发了超时异常！！
        {badrpc, timeout} -> {error, {channel_operation_timeout, Timeout}};
        {badrpc, Reason}  -> {error, Reason};
        {_, Bads} ->
            case lists:filter(
                   fun ({_Pid, {exit, {R, _}, _}}) ->
                           rabbit_misc:is_abnormal_exit(R);
                       ({_Pid, _})                 -> false
                   end, Bads) of
                []    -> ok;
                Bads1 -> {error, Bads1}
            end;
        Error         -> {error, Error}
    end.

```

从这里可以看出根本的原因是：在 5 秒时间内没有完成“将 channel 关闭信息通知给相关 queue“的通知工作，导致发生了 rpc 调用 timeout 异常；

#### 原因总结

虽然从代码分析中已经能够确认问题是由于 rpc 调用超时导致的异常，但这里仍旧有问题需要弄清楚：
- 多处崩溃信息的先后顺序是？
- 导致 rpc 调用超时的原因是什么？网络状况不好？超时参数设置的过小？

针对第一个问题，重新回顾一下上面的调用栈：
```shell
     Reason:  {{badmatch,{error,{channel_operation_timeout,5000}}},
               [{rabbit_channel,terminate,2,[{file,"src/rabbit_channel.erl"},{line,614}]},
                {gen_server2,terminate,3,[{file,"src/gen_server2.erl"},{line,1146}]},
                {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,249}]}]}
```

我们可以采取反向推理的方式得出结论：
- 在通过 rpc 通知 channel 挂掉消息时发生了 timeout 超时；
- rpc 调用发生在 rabbit_channel:terminate/2 中，用于在当前 channel 终止时，通知与其相关的所有 queue ；并且这些 queue 既可能存在于本地节点，也可能存在于远端节点；
- rabbit_channel:terminate/2 调用发生在 gen_server2:terminate/3 中，并采用 catch 进行了异常捕获；由于成功捕获到 timeout 超时异常，在输出“=ERROR REPORT====“后，通过 exit/1 调用终止当前调用进程；
- gen_server2:terminate/3 是在 proc_lib:wake_up/3 中调用的，而该函数是在进程进入休眠状态时设置的回调；该回调的触发条件是在休眠状态下收到一条消息即可；
- 由上下文可知，rabbit_channel 进程收到的这条消息为 {'EXIT',<0.3384.6141>,shutdown} ，其中 <0.3384.6141> 为 rabbit_channel_sup 进程 pid ；


----------


# 其他错误

```
=ERROR REPORT==== 3-Sep-2016::12:05:44 ===
Channel error on connection <0.15869.1025> (10.0.29.67:22814 -> 10.0.22.20:5672, vhost: 'risk', user: 'risk'), channel 1:
operation queue.declare caused a channel exception precondition_failed: "inequivalent arg 'durable' for queue 'davincimq' in vhost 'risk': received 'true' but current is 'false'"
```




```
=ERROR REPORT==== 3-Sep-2016::12:09:06 ===
Channel error on connection <0.6431.1025> (10.0.28.137:48391 -> 10.0.22.20:5672, vhost: 'risk', user: 'risk'), channel 1:
operation queue.declare caused a channel exception not_found: "no queue 'davincimq' in vhost 'risk'"
```


```
=ERROR REPORT==== 3-Sep-2016::12:14:24 ===
Error on AMQP connection <0.13356.1165>: enotconn (socket is not connected)
```


```
=ERROR REPORT==== 3-Sep-2016::12:18:39 ===
closing AMQP connection <0.1920.1146> (10.0.252.30:56126 -> 10.0.22.20:5672):
{handshake_timeout,handshake}
```


```
=ERROR REPORT==== 3-Sep-2016::12:20:12 ===
Error on AMQP connection <0.22484.5286> (10.0.48.131:26125 -> 10.0.22.20:5672, vhost: 'risk', user: 'risk', state: running), channel 0:
operation none caused a connection exception connection_forced: "broker forced connection closure with reason 'shutdown'"
```



```
=ERROR REPORT==== 3-Sep-2016::12:20:27 ===
Channel error on connection <0.26957.1080> (10.0.23.152:34791 -> 10.0.22.20:5672, vhost: 'risk_biz_marketing', user: 'risk_biz_marketing_user'), channel 1:
operation basic.consume caused a channel exception not_found: "no queue 'vangogh_biz_marketing' in vhost 'risk_biz_marketing'"
```



